version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - restapiapp/.env
    networks:
      - restapi-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: mr.green
      POSTGRES_PASSWORD: 280992
      POSTGRES_DB: dbrestapi
    ports:
      - "5432:5432"
    networks:
      - restapi-network
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "mr.green", "-d", "dbrestapi" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  redis:
    image: redis:latest
    ports:
      - "6381:6379"
    networks:
      - restapi-network
    restart: always

networks:
  restapi-network:
    driver: bridge
