version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user       # Вкажіть ім'я користувача
      RABBITMQ_DEFAULT_PASS: password    # Вкажіть пароль
    ports:
      - "5672:5672"                      # Порт для AMQP
      - "15672:15672"                    # Порт для веб-інтерфейсу
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Зберігання даних RabbitMQ

volumes:
  rabbitmq_data:
